### ISSUE TITLE
This Repo has been excluded from Hacktoberfest.

### ISSUE THREAD

**Issue by souvikpal2000** [puruagarwal1/hacktoberfest-2022-directory#107]
![image](https://user-images.githubusercontent.com/64771649/193438564-b017a0ef-9b0c-44ec-acf8-46b6aeb3b076.png)

**Comment by ItzLevvie** [comment]
This repository has been **_permanently_** excluded from Hacktoberfest 2022. This means that any pull requests (PRs) made to this repository **_will_** not be counted towards your contributions for Hacktoberfest 2022.

Please contribute to **_valuable_** repositories instead of sending pull requests (PRs) to repositories that are there to defeat the whole purpose of Hacktoberfest 2022.

Any repeated, continuous exclusions will automatically ban your account from participating in Hacktoberfest 2022.
